name: Test

on: 
 push:
 pull_request:

jobs:
  vagrant-up:
    runs-on: macos-10.15

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v2
        
      - name: Installing required packages...
        run: brew install openssl curl

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: test if running
        run: |
          result=$(curl -Is https://192.168.10.108/ | head -1 | grep -o '[0-9][0-9][0-9]');
          [[ "$result" == "200" ]];
