name: Test

on: 
 push:
 pull_request:

jobs:
  test:
    runs-on: macos-10.15

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Installing required packages...
        run: brew install openssl curl

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
            
      - name: Generate SSH key if not exist
        run: |
          if [[ ! -f "~/.ssh/id_rsa" ]]; then
            ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
          fi;

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: test if running
        run: |
          curl_fetch=$(curl -Is http://localhost:8000/);
          curl_fetch="${curl_fetch//'%'/'%25'}";
          curl_fetch="${curl_fetch//$'\n'/'%0A'}";
          curl_fetch="${curl_fetch//$'\r'/'%0D'}";
          curl_code=$(echo "$curl_fetch" | head -1 | grep -o '[0-9][0-9][0-9]');
          [[ "$curl_code" == "200" ]] || [[ "$curl_code" == "302" ]];
