name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-10.15

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Installing required packages...
        run: brew install openssl curl

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Generate SSH key if not exist
        run: |
          if [[ ! -f "~/.ssh/id_rsa" ]]; then
            ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
          fi;

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: test if running
        run: |
          curl_code=$(curl -Is http://localhost:8000/ | head -1 | grep -o '[0-9][0-9][0-9]');         
          echo "::set-output name=curl_code::$curl_code";
          [[ "$curl_code" == "200" ]] || [[ "$curl_code" == "302" ]];

      - name: Run vagrant halt
        run: vagrant halt --force

  auto-approve:
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    runs-on: ubuntu-latest
    needs:
      - auto-approve
    if: github.event.review.state == 'approved'
    steps:
      - name: Enable Github Automerge
        uses: alexwilson/enable-github-automerge-action@1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
