name: Test

on: 
 push:
 pull_request:

jobs:
  test:
    runs-on: macos-10.15

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Installing required packages...
        run: brew install openssl curl

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
            
      - name: Generate SSH key if not exist
        run: |
          if [[ ! -f "~/.ssh/id_rsa" ]]; then
            ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
          fi;

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up
        
      - name: Running CURL command
        id: curl_fetch
        run: |          
          content=$(curl -Is https://localhost:8000/)
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=curl_fetch::$content"
          
      - name: Getting curl return code
        id: curl_code
        run: |
          content=$(echo "${{ needs.test.outputs.curl_fetch }}" | head -1 | grep -o '[0-9][0-9][0-9]')
          echo "::set-output name=curl_code::$content"

      - name: test if running
        run: |
          [[ "${{ needs.test.outputs.curl_code }}" == "200" ]];
