name: Auto update project Wiki

on:
  push:
    #branches:
    #  - master
    #tags:
    #  - 'v*' # Initializes on any new tag
    #paths:
    #  - .github/workflows/update-wiki.yml
    #  - '**.js'
    #  - '**.php'

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting main code
        uses: actions/checkout@v2
      - name: Parsing git info
        run: |
          echo "::set-env name=LAST_COMMIT_AUTHOR_EMAIL::$(git show -s --format='%ae' HEAD)"
          echo "::set-env name=LAST_COMMIT_AUTHOR_NAME::$(git show -s --format='%an' HEAD)"
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          if [ "$BRANCH_NAME" == 'HEAD' ]; then
            BRANCH_NAME=$(git describe --tags --abbrev=0)
          fi;
          BRANCH_NAME=master
          echo "::set-env name=BRANCH_NAME::$BRANCH_NAME"
      - name: Checking for required secrets
        run: |
          if [ -z "${{ secrets.WIKI_GITHUB_UPDATE_TOKEN }}" ]; then
            echo "Secret WIKI_GITHUB_UPDATE_TOKEN is missing. Use this link to create required token -> https://github.com/settings/tokens/new?scopes=repo&description=wiki%20api%20generator <- and than add to project secrets."
            exit 1
          fi;
          if [ -z "${{ secrets.WIKI_GITHUB_UPDATE_USER }}" ]; then
            echo "Secret WIKI_GITHUB_UPDATE_USER is missing. Set this to username for who token belongs."
            exit 2
          fi;
      - name: Cloning old wiki
        run: |
          mkdir .docs.old
          cd .docs.old
          git init
          git remote add origin https://${{ secrets.WIKI_GITHUB_UPDATE_USER }}:${{ secrets.WIKI_GITHUB_UPDATE_TOKEN }}@github.com/${{ github.repository	}}.wiki.git
          git config --local gc.auto 0
          git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin
          git checkout ${BRANCH_NAME} 2>/dev/null || git checkout -b ${BRANCH_NAME}
          git reset --hard
          cd ..
      - name: Installing hidden clean/phpdoc-md
        run: composer require --dev clean/phpdoc-md
      - name: Creating .docs dir
        run: mkdir -p .docs
      - name: Creating configuration
        run: |
          cat > .phpdoc-md <<'EOF'
          <?php
          return (object)[
              'rootNamespace' => 'ImpressCMS',
              'destDirectory' => '.docs',
              'format' => 'github',
              'classes' => array_unique(
                  array_filter(
                      array_merge(
                          array_map(
                              function ($file) {
                                  return substr(str_replace(['./core/', '/'], ['\\ImpressCMS\\Core\\', '\\'], $file), 0, -4);
                              },
                              glob('./core/**/*.php')
                          ),
                          array_map(
                              function ($file) {
                                  return substr(str_replace(['./libraries/icms/', '/'], ['icms_', '_'], $file), 0, -4);
                              },
                              glob('./libraries/icms/**/*.php')
                          )
                      ),
                      function ($item) {
                          return class_exists($item) && !in_array($item, ['\icms_image_Object']);
                      }
                  )
              ),
          ];
          EOF
      - name: View config
        run: cat .phpdoc-md
      - name: Genereting docs...
        run: ./bin/phpdoc-md
      - name: Updating docs folder
        run: cp -r ./.docs.old/.git ./.docs/.git
      - name: Renaming README.md -> HOME.md
        working-directory: .docs/
        run: mv README.md HOME.md
      - name: Adding extra info to HOME.md
        working-directory: .docs/
        run: |
          shopt -s globstar
          for i in **/*.md; do
            echo "Fixing links in $i..."
            OLD_SIZE=$(stat --printf="%s" "$i")
            php -r 'file_put_contents($argv[1], preg_replace("/\(.+\/(.+)\.md\)/m", "($1)", file_get_contents($argv[1])));' -- "$i"
            NEW_SIZE=$(stat --printf="%s" "$i")
            if [ "$OLD_SIZE" -ne "$NEW_SIZE" ]; then
              echo "  Changed."
            fi;
          done
          sed -i '1i##### Notice: Wiki was automatic generated from project sources as project API documentation. Do not edit manually!' HOME.md
          sed -i "2i\ " HOME.md
      - name: Configuring commit author
        working-directory: .docs/
        run: |
          git config --local user.email "$LAST_COMMIT_AUTHOR_EMAIL"
          git config --local user.name "$LAST_COMMIT_AUTHOR_NAME"
      - name: Checking what docs where updated
        working-directory: .docs/
        run: git status
      - name: Commiting docs update
        working-directory: .docs/
        run: |
          git add -u :/
          git add .
          git commit -m "Automatically generated for https://github.com/${{ github.repository }}/commit/${GITHUB_SHA}" || true
      - name: Pushing docs update
        working-directory: .docs/
        run: git push -u origin ${BRANCH_NAME}